### ISSUE TITLE
Team Ocicat Review

### ISSUE THREAD

**Issue by cod3smith** [yahir91/Enumerables#1]
Hey @MarilenaRoque and @yahir91.
Great job on the project :partying_face: :partying_face: . We really liked the progress you've made on your project :sunglasses: . Here are somethings we thought you should work on: 
- [x] Use array to store arguments.
- [x] Use return enum if no block is given.
- [x] Optimize your code by using yield once and saving result in a variable and check against the variable.
- [x] Check documentations and see the different use cases of different methods.
- [x] For my_any, you should be checking against regular expressions.
- [x] Reduce the if...else conditions.
- [x] Use intuitive variable names.

Again, great job and happy coding :woman_technologist:

**Comment by MarilenaRoque** [comment]
Hey team! :smile: 
I am happy to say that we have implemented all the suggestions and our code looks cleaner, more effective, and more concise. 
Thank you so much for the comprehensive and helpful review! :rocket:
