### ISSUE TITLE
Morning session

### ISSUE THREAD

**Issue by jessicafarias** [yahir91/Enumerables#4]
Excellent work! You did an awesome job.
We can notice that you are not using the Test-RSpec tool, it could be useful for your future projects.
https://github.com/microverseinc/linters-config/tree/master/ruby

**Comment by MarilenaRoque** [comment]
Hello, @jessicafarias and all the team! :+1: 
I have read about this tool and definitely will apply on the next projects! 
It makes the process to test the code really easier. 
Thank you so much for the review!
